import type { NextPage } from 'next'
import Head from 'next/head'
import Cadastrar from '../components/Cadastrar'
import ImagemInfo from '../components/ImagemInfo'
import * as S from "./home.styles"

const Home: NextPage = () => {
  

  return (
    <div>
      <Head>
        <title>Teste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='crossorigin' />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet" />
      </Head>

      <S.SessaoCadastrar>
        <Cadastrar />
        <ImagemInfo />
      </S.SessaoCadastrar>
    </div>
  )
}

export default Home
