import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";

const Home: NextPage = () => {
  const [dataForm, setDataForm] = useState({
    name: "",
    lastName: "",
    email: "",
    birthDate: "",
    password: "",
    country: "",
    bio: "",
  });

  const onChangeInput = (e) =>
    setDataForm({ ...dataForm, [e.target.name]: e.target.value });

  const sendRegistration = async (e) => {
    e.preventDefault();
    console.log(dataForm.name);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="robots" content="index/follow" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="crossorigin"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <h1>Cadastre-se</h1>
        <p>Para começar, insira os dados abaixo:</p>
        <form onSubmit={sendRegistration}>
          <input
            type="text"
            name="name"
            placeholder="Nome"
            onChange={onChangeInput}
            value={dataForm.name}
          ></input>
          <br />
          <input type="text" name="lastName" placeholder="Sobrenome"></input>
          <br />
          <input type="email" name="email" placeholder="E-mail"></input>
          <br />
          <input
            type="text"
            name="birthDate"
            placeholder="Data de nascimento"
          ></input>
          <br />
          <input type="password" name="password" placeholder="Senha"></input>
          <br />
          <input
            type="text"
            name="country"
            placeholder="Selecione seu país"
          ></input>
          <br />
          <input type="text" name="bio" placeholder="Bio"></input>
          <br />
          <button type="submit">Cadastrar</button>
          <br />
          <input type="checkbox"></input>
          <br />
        </form>
      </div>
    </div>
  );
};

export default Home;
